[haproxy]
haproxy ansible_host=10.122.0.5

[nginx]
nginx ansible_host=10.122.0.4

[apache]
apache ansible_host=10.122.0.3

[backend]
nginx ansible_host=10.122.0.4
apache ansible_host=10.122.0.3

[all:vars]
ansible_python_interpreter=/usr/bin/python3
