---
- name: Configure Nginx backend
  hosts: nginx
  become: true
  roles:
    - nginx

- name: Configure Apache backend
  hosts: apache
  become: true
  roles:
    - apache

- name: Configure HAProxy load balancer
  hosts: haproxy
  become: true
  roles:
    - haproxy